### ISSUE TITLE
GL state is not returned to normal tile entity rendering after beams

### ISSUE THREAD

**Issue by LatvianModder** [p455w0rd/XPTeleporters-2#1]
Which results in other things like chests to have incorrect blending/lighting mode
![2019-05-15_15 45 21](https://user-images.githubusercontent.com/3844385/57776948-65fdb100-7729-11e9-9dbd-196560091a88.png)

**Comment by p455w0rd** [comment]
i did not even see this until now...thank you..i'll get it fixed

**Comment by p455w0rd** [comment]
I'm doing my best to reproduce, but not having any success. Can I get a list of mods used in this instance?
