### ISSUE TITLE
java.lang.NullPointerException: Rendering Block Entity

### ISSUE THREAD

**Issue by aaronhowser1** [p455w0rd/XPTeleporters-2#4]
Not my crash, but someone playing Academy made this issue: FTBTeam/FTB-Academy/issues/214

[Link to crash report](https://gist.github.com/Patrity/d4860c5ffac4fe0f576fefa0d25d28dd)

**Comment by p455w0rd** [comment]
I commented over at [FTBTeam/FTB_Academy/issues/214](https://github.com/FTBTeam/FTB-Academy/issues/214#issuecomment-554840466)
This shouldn't be happening in 2.0.2. I do remember working on this specifically, just not 100% on exactly when I addressed it. So, I'll leave this issue open until I get response from the user when they try 2.0.2.
